#!/usr/bin/env bun
/**
 * Sync scores from the 7 environment repos into platform data files.
 *
 * Reads runs/*.json from each env repo, computes mean scores per task per model,
 * and writes src/data/heatmap.ts with fresh data.
 *
 * Usage:
 *   bun run scripts/sync-scores.ts
 *   bun run scripts/sync-scores.ts --envs-dir /home/aidanby
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "fs";
import { join, resolve } from "path";

const ENV_MAP: Record<string, { dir: string; slug: string }> = {
  "hw-cbmc-env": { dir: "hw-cbmc-env", slug: "hw-cbmc" },
  "lean-demo": { dir: "lean-demo", slug: "lean-theorem-proving" },
  "csparse-rust-env": { dir: "csparse-rust-env", slug: "c-to-rust" },
  "congestion-control": { dir: "congestion-control", slug: "congestion-control" },
  "distributed-consensus": { dir: "distributed-consensus", slug: "distributed-consensus" },
  "cedar-env": { dir: "cedar-env", slug: "cedar-policy-verification" },
  "computational-biology": { dir: "computational-biology", slug: "computational-biology" },
};

const MODEL_ORDER = [
  "claude-sonnet-4-6",
  "gemini-2.5-flash",
  "gemini-3.1-pro-preview",
  "kimi-k2.5",
  "mistral-large-3",
];

interface RunResult {
  task: string;
  score: number | null;
  tool_calls_total?: number;
  errors?: string[];
}

interface RunFile {
  model?: string;
  results: RunResult[];
}

function loadEnvScores(
  runsDir: string,
): Record<string, Record<string, number>> {
  // { model: { task: meanScore } }
  const allScores: Record<string, Record<string, number[]>> = {};

  if (!existsSync(runsDir)) return {};

  for (const file of readdirSync(runsDir).sort()) {
    if (!file.endsWith(".json") || !file.includes("_run")) continue;

    const model = file.replace(/_run\d+\.json$/, "");
    if (!MODEL_ORDER.includes(model)) continue;

    try {
      const data: RunFile = JSON.parse(
        readFileSync(join(runsDir, file), "utf-8"),
      );

      for (const r of data.results || []) {
        if (r.score === null || r.score === undefined) continue;

        // Normalize task names: hyphens -> underscores
        const task = r.task.replace(/-/g, "_");

        if (!allScores[model]) allScores[model] = {};
        if (!allScores[model][task]) allScores[model][task] = [];
        allScores[model][task].push(r.score);
      }
    } catch {
      // Skip malformed files
    }
  }

  // Compute means
  const means: Record<string, Record<string, number>> = {};
  for (const [model, tasks] of Object.entries(allScores)) {
    means[model] = {};
    for (const [task, scores] of Object.entries(tasks)) {
      means[model][task] = scores.reduce((a, b) => a + b, 0) / scores.length;
    }
  }

  return means;
}

function generateHeatmapTs(
  allData: Record<string, Record<string, Record<string, number>>>,
): string {
  const lines: string[] = [
    '/**',
    ' * Heatmap data — per-task scores for every model x environment combination.',
    ' *',
    ` * Auto-generated by scripts/sync-scores.ts on ${new Date().toISOString().split("T")[0]}.`,
    ' * Do not edit manually.',
    ' */',
    '',
    'export type HeatmapCell = { task: string; score: number };',
    '',
    'export type EnvironmentHeatmap = { [modelSlug: string]: HeatmapCell[] };',
    '',
    'export const REAL_HEATMAP_DATA: Record<string, EnvironmentHeatmap> = {',
  ];

  for (const [envSlug, modelData] of Object.entries(allData)) {
    lines.push(`  "${envSlug}": {`);

    for (const model of MODEL_ORDER) {
      if (!modelData[model]) continue;

      const tasks = Object.entries(modelData[model])
        .sort(([, a], [, b]) => a - b) // sorted by score ascending
        .map(([task, score]) => `      { task: "${task}", score: ${score} }`);

      lines.push(`    "${model}": [`);
      lines.push(tasks.join(",\n"));
      lines.push("    ],");
    }

    lines.push("  },");
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// Main
const args = process.argv.slice(2);
let envsDir = resolve(process.env.HOME || "/home/aidanby");

const dirArgIdx = args.indexOf("--envs-dir");
if (dirArgIdx !== -1 && args[dirArgIdx + 1]) {
  envsDir = resolve(args[dirArgIdx + 1]);
}

console.log(`Syncing scores from ${envsDir}...`);

const allData: Record<string, Record<string, Record<string, number>>> = {};
let totalTasks = 0;
let totalScores = 0;

for (const [envKey, { dir, slug }] of Object.entries(ENV_MAP)) {
  const runsDir = join(envsDir, dir, "runs");
  const modelData = loadEnvScores(runsDir);

  if (Object.keys(modelData).length > 0) {
    allData[slug] = modelData;

    const taskCount = new Set(
      Object.values(modelData).flatMap((m) => Object.keys(m)),
    ).size;
    const scoreCount = Object.values(modelData).reduce(
      (acc, m) => acc + Object.keys(m).length,
      0,
    );

    console.log(
      `  ${slug}: ${taskCount} tasks, ${Object.keys(modelData).length} models, ${scoreCount} scores`,
    );
    totalTasks += taskCount;
    totalScores += scoreCount;
  } else {
    console.log(`  ${slug}: no run data found in ${runsDir}`);
  }
}

const output = generateHeatmapTs(allData);
const outPath = join(__dirname, "..", "src", "data", "heatmap.ts");
writeFileSync(outPath, output);

console.log(
  `\nWritten: ${outPath}\nTotal: ${totalTasks} tasks, ${totalScores} model-task scores across ${Object.keys(allData).length} envs`,
);
